// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: skeleton/api/rpcmessage/message.proto

package rpcmessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCOAuthLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCOAuthLoginRequest) Reset() {
	*x = RPCOAuthLoginRequest{}
	mi := &file_skeleton_api_rpcmessage_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCOAuthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCOAuthLoginRequest) ProtoMessage() {}

func (x *RPCOAuthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skeleton_api_rpcmessage_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCOAuthLoginRequest.ProtoReflect.Descriptor instead.
func (*RPCOAuthLoginRequest) Descriptor() ([]byte, []int) {
	return file_skeleton_api_rpcmessage_message_proto_rawDescGZIP(), []int{0}
}

func (x *RPCOAuthLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RPCOAuthLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RPCOAuthLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCOAuthLoginResponse) Reset() {
	*x = RPCOAuthLoginResponse{}
	mi := &file_skeleton_api_rpcmessage_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCOAuthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCOAuthLoginResponse) ProtoMessage() {}

func (x *RPCOAuthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skeleton_api_rpcmessage_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCOAuthLoginResponse.ProtoReflect.Descriptor instead.
func (*RPCOAuthLoginResponse) Descriptor() ([]byte, []int) {
	return file_skeleton_api_rpcmessage_message_proto_rawDescGZIP(), []int{1}
}

func (x *RPCOAuthLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_skeleton_api_rpcmessage_message_proto protoreflect.FileDescriptor

var file_skeleton_api_rpcmessage_message_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72,
	0x70, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x14, 0x52, 0x50, 0x43, 0x4f, 0x41,
	0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x50, 0x43, 0x4f, 0x41, 0x75, 0x74,
	0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x42, 0xb3, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x70, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x72, 0x63, 0x79, 0x6c, 0x61, 0x6e,
	0x39, 0x38, 0x2f, 0x6d, 0x69, 0x6e, 0x6f, 0x74, 0x61, 0x75, 0x72, 0x2f, 0x73, 0x6b, 0x65, 0x6c,
	0x65, 0x74, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0xa2, 0x02, 0x03, 0x41, 0x52, 0x58, 0xaa, 0x02, 0x0e, 0x41, 0x70, 0x69, 0x2e,
	0x52, 0x70, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0xca, 0x02, 0x0e, 0x41, 0x70, 0x69,
	0x5c, 0x52, 0x70, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0xe2, 0x02, 0x1a, 0x41, 0x70,
	0x69, 0x5c, 0x52, 0x70, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x41, 0x70, 0x69, 0x3a, 0x3a,
	0x52, 0x70, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_skeleton_api_rpcmessage_message_proto_rawDescOnce sync.Once
	file_skeleton_api_rpcmessage_message_proto_rawDescData = file_skeleton_api_rpcmessage_message_proto_rawDesc
)

func file_skeleton_api_rpcmessage_message_proto_rawDescGZIP() []byte {
	file_skeleton_api_rpcmessage_message_proto_rawDescOnce.Do(func() {
		file_skeleton_api_rpcmessage_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_skeleton_api_rpcmessage_message_proto_rawDescData)
	})
	return file_skeleton_api_rpcmessage_message_proto_rawDescData
}

var file_skeleton_api_rpcmessage_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_skeleton_api_rpcmessage_message_proto_goTypes = []any{
	(*RPCOAuthLoginRequest)(nil),  // 0: api.rpcmessage.RPCOAuthLoginRequest
	(*RPCOAuthLoginResponse)(nil), // 1: api.rpcmessage.RPCOAuthLoginResponse
}
var file_skeleton_api_rpcmessage_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skeleton_api_rpcmessage_message_proto_init() }
func file_skeleton_api_rpcmessage_message_proto_init() {
	if File_skeleton_api_rpcmessage_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skeleton_api_rpcmessage_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skeleton_api_rpcmessage_message_proto_goTypes,
		DependencyIndexes: file_skeleton_api_rpcmessage_message_proto_depIdxs,
		MessageInfos:      file_skeleton_api_rpcmessage_message_proto_msgTypes,
	}.Build()
	File_skeleton_api_rpcmessage_message_proto = out.File
	file_skeleton_api_rpcmessage_message_proto_rawDesc = nil
	file_skeleton_api_rpcmessage_message_proto_goTypes = nil
	file_skeleton_api_rpcmessage_message_proto_depIdxs = nil
}
