// Code generated by protoc-gen-minotaur-vivid-typed. DO NOT EDIT.
// versions:
//  protoc-gen-minotaur-vivid-typed 1.0.0
//  protoc           v4.25.3
// source: typed_test.proto

package test

import (
	vivid "github.com/kercylan98/minotaur/engine/vivid"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

var _ *emptypb.Empty

// Test is the typed service of test.Test
type Test interface {
	// Ping is the typed method of test.Test.Ping
	Ping(ctx vivid.ActorContext, message *PingRequest) (*PingResponse, error)
	// Tell is the typed method of test.Test.Tell
	Tell(ctx vivid.ActorContext, message *PingRequest)
}
