// Code generated by Minotaur. DO NOT EDIT.

package datasheet

import (
	"github.com/kercylan98/minotaur/engine/datasheet"
	"sync"
	"time"
)

var _ = (*time.Time)(nil)

type DatasheetSign = string

const (
	// GlobalSign 标准模板
	GlobalSign DatasheetSign = "Global"
	// ActivitySign 索引模板
	ActivitySign DatasheetSign = "Activity"
)

var loaded = make(map[DatasheetSign]bool)
var loadLock sync.RWMutex
var upLock sync.RWMutex
var (
	_Global    *Global
	__Global   *Global
	_Activity  map[int]map[int]*Activity
	__Activity map[int]map[int]*Activity
)

var (
	generators = map[DatasheetSign]func() any{
		GlobalSign:   func() any { return new(*Global) },
		ActivitySign: func() any { return make(map[int]map[int]*Activity) },
	}

	loaders = map[DatasheetSign]func(any){
		GlobalSign:   func(data any) { __Global = data.(*Global) },
		ActivitySign: func(data any) { __Activity = data.(map[int]map[int]*Activity) },
	}

	updaters = map[DatasheetSign]func(){
		GlobalSign:   func() { _Global, __Global = __Global, nil },
		ActivitySign: func() { _Activity, __Activity = __Activity, nil },
	}

	getters = map[DatasheetSign]func() any{
		GlobalSign:   func() any { return __Global },
		ActivitySign: func() any { return __Activity },
	}
)

// Awards 一堆奖励
type Awards []*Award

// Award 通用奖励
type Award struct {
	Id    int
	Count int
}

// PlayerAward 玩家奖励
type PlayerAward struct {
	Id     string
	Awards []Award
}

// Global 标准模板
type Global struct {
	NewbieAwards []Award          // 新手奖励
	InitCoins    datasheet.BigInt // 初始金币
}

// Activity 索引模板
type Activity struct {
	Id     int     // 活动 ID
	Day    int     // 轮转天数
	Awards []Award // 奖励
}

// Load 传入一个处理器，该函数会将所需加载的数据表名称及其接收反序列化数据的实例传入，如果 loaded 为 false，那么该数据表将不会被加载，后续可通过 Up 或 UpAll 函数将加载的数据转换为线上的数据
//  - 如果处理器返回错误，则加载过程将中断，任何内容都不会改变
func Load(handler func(sign DatasheetSign, data any) (loaded bool, err error)) error {
	temp := make(map[DatasheetSign]any)
	temp[GlobalSign] = generators[GlobalSign]()
	temp[ActivitySign] = generators[ActivitySign]()

	for sign, datasheet := range temp {
		loaded, err := handler(sign, datasheet)
		if err != nil {
			return err
		}
		if !loaded {
			delete(temp, sign)
		}
	}

	loadLock.Lock()
	defer loadLock.Unlock()
	for sign, datasheet := range temp {
		loaded[sign] = true
		loaders[sign](datasheet)
	}

	return nil
}

// UpAll 将所有加载的数据转换为线上的数据，并且将当前已加载的数据清空，需再次通过 Load 才能再次加载数据，否则将没有任何效果
func UpAll() {
	loadLock.RLock()
	loadLock.RUnlock()

	upLock.Lock()
	defer upLock.Unlock()

	for sign, updater := range updaters {
		if !loaded[sign] {
			continue
		}
		updater()
	}

	return
}

// Up 将指定加载的数据转换为线上的数据，并且将当前已加载的数据清空，需再次通过 Load 才能再次加载数据，否则将没有任何效果
func Up(signs ...DatasheetSign) {
	loadLock.RLock()
	loadLock.RUnlock()

	upLock.Lock()
	defer upLock.Unlock()

	for _, sign := range signs {
		if !loaded[sign] {
			continue
		}
		updaters[sign]()
	}
}

// GetGlobal 标准模板
//  - 修改获取到的数据表数据将可能导致竞态问题，需谨慎写操作
func GetGlobal() *Global {
	loadLock.RLock()
	defer loadLock.RUnlock()
	return _Global
}

// GetActivity 索引模板
//  - 修改获取到的数据表数据将可能导致竞态问题，需谨慎写操作
func GetActivity() map[int]map[int]*Activity {
	loadLock.RLock()
	defer loadLock.RUnlock()
	return _Activity
}

// GetDatasheet 根据签名获取数据表
//  - 修改获取到的数据表数据将可能导致竞态问题，需谨慎写操作
func GetDatasheet(sign DatasheetSign) any {
	loadLock.RLock()
	defer loadLock.RUnlock()
	return getters[sign]()
}
