// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: engine/vivid/typed/test/typed_test.proto

package testconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	options "github.com/kercylan98/minotaur/engine/vivid/typed/options"
	test "github.com/kercylan98/minotaur/engine/vivid/typed/test"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestName is the fully-qualified name of the Test service.
	TestName = "engine.vivid.typed.test.Test"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestSayProcedure is the fully-qualified name of the Test's Say RPC.
	TestSayProcedure = "/engine.vivid.typed.test.Test/Say"
	// TestCallProcedure is the fully-qualified name of the Test's Call RPC.
	TestCallProcedure = "/engine.vivid.typed.test.Test/Call"
	// TestPingProcedure is the fully-qualified name of the Test's Ping RPC.
	TestPingProcedure = "/engine.vivid.typed.test.Test/Ping"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	testServiceDescriptor    = test.File_engine_vivid_typed_test_typed_test_proto.Services().ByName("Test")
	testSayMethodDescriptor  = testServiceDescriptor.Methods().ByName("Say")
	testCallMethodDescriptor = testServiceDescriptor.Methods().ByName("Call")
	testPingMethodDescriptor = testServiceDescriptor.Methods().ByName("Ping")
)

// TestClient is a client for the engine.vivid.typed.test.Test service.
type TestClient interface {
	Say(context.Context, *connect.Request[test.Request]) (*connect.Response[options.Empty], error)
	Call(context.Context, *connect.Request[test.Request]) (*connect.Response[test.Response], error)
	Ping(context.Context, *connect.Request[test.Request]) (*connect.Response[test.Response], error)
}

// NewTestClient constructs a client for the engine.vivid.typed.test.Test service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &testClient{
		say: connect.NewClient[test.Request, options.Empty](
			httpClient,
			baseURL+TestSayProcedure,
			connect.WithSchema(testSayMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		call: connect.NewClient[test.Request, test.Response](
			httpClient,
			baseURL+TestCallProcedure,
			connect.WithSchema(testCallMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[test.Request, test.Response](
			httpClient,
			baseURL+TestPingProcedure,
			connect.WithSchema(testPingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// testClient implements TestClient.
type testClient struct {
	say  *connect.Client[test.Request, options.Empty]
	call *connect.Client[test.Request, test.Response]
	ping *connect.Client[test.Request, test.Response]
}

// Say calls engine.vivid.typed.test.Test.Say.
func (c *testClient) Say(ctx context.Context, req *connect.Request[test.Request]) (*connect.Response[options.Empty], error) {
	return c.say.CallUnary(ctx, req)
}

// Call calls engine.vivid.typed.test.Test.Call.
func (c *testClient) Call(ctx context.Context, req *connect.Request[test.Request]) (*connect.Response[test.Response], error) {
	return c.call.CallUnary(ctx, req)
}

// Ping calls engine.vivid.typed.test.Test.Ping.
func (c *testClient) Ping(ctx context.Context, req *connect.Request[test.Request]) (*connect.Response[test.Response], error) {
	return c.ping.CallUnary(ctx, req)
}

// TestHandler is an implementation of the engine.vivid.typed.test.Test service.
type TestHandler interface {
	Say(context.Context, *connect.Request[test.Request]) (*connect.Response[options.Empty], error)
	Call(context.Context, *connect.Request[test.Request]) (*connect.Response[test.Response], error)
	Ping(context.Context, *connect.Request[test.Request]) (*connect.Response[test.Response], error)
}

// NewTestHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestHandler(svc TestHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testSayHandler := connect.NewUnaryHandler(
		TestSayProcedure,
		svc.Say,
		connect.WithSchema(testSayMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	testCallHandler := connect.NewUnaryHandler(
		TestCallProcedure,
		svc.Call,
		connect.WithSchema(testCallMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	testPingHandler := connect.NewUnaryHandler(
		TestPingProcedure,
		svc.Ping,
		connect.WithSchema(testPingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/engine.vivid.typed.test.Test/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestSayProcedure:
			testSayHandler.ServeHTTP(w, r)
		case TestCallProcedure:
			testCallHandler.ServeHTTP(w, r)
		case TestPingProcedure:
			testPingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestHandler returns CodeUnimplemented from all methods.
type UnimplementedTestHandler struct{}

func (UnimplementedTestHandler) Say(context.Context, *connect.Request[test.Request]) (*connect.Response[options.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("engine.vivid.typed.test.Test.Say is not implemented"))
}

func (UnimplementedTestHandler) Call(context.Context, *connect.Request[test.Request]) (*connect.Response[test.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("engine.vivid.typed.test.Test.Call is not implemented"))
}

func (UnimplementedTestHandler) Ping(context.Context, *connect.Request[test.Request]) (*connect.Response[test.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("engine.vivid.typed.test.Test.Ping is not implemented"))
}
