// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: engine/prc/shared.proto

package prcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	prc "github.com/kercylan98/minotaur/engine/prc"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SharedName is the fully-qualified name of the Shared service.
	SharedName = "engine.prc.Shared"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SharedStreamHandlerProcedure is the fully-qualified name of the Shared's StreamHandler RPC.
	SharedStreamHandlerProcedure = "/engine.prc.Shared/StreamHandler"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	sharedServiceDescriptor             = prc.File_engine_prc_shared_proto.Services().ByName("Shared")
	sharedStreamHandlerMethodDescriptor = sharedServiceDescriptor.Methods().ByName("StreamHandler")
)

// SharedClient is a client for the engine.prc.Shared service.
type SharedClient interface {
	StreamHandler(context.Context) *connect.BidiStreamForClient[prc.SharedMessage, prc.SharedMessage]
}

// NewSharedClient constructs a client for the engine.prc.Shared service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSharedClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SharedClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &sharedClient{
		streamHandler: connect.NewClient[prc.SharedMessage, prc.SharedMessage](
			httpClient,
			baseURL+SharedStreamHandlerProcedure,
			connect.WithSchema(sharedStreamHandlerMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// sharedClient implements SharedClient.
type sharedClient struct {
	streamHandler *connect.Client[prc.SharedMessage, prc.SharedMessage]
}

// StreamHandler calls engine.prc.Shared.StreamHandler.
func (c *sharedClient) StreamHandler(ctx context.Context) *connect.BidiStreamForClient[prc.SharedMessage, prc.SharedMessage] {
	return c.streamHandler.CallBidiStream(ctx)
}

// SharedHandler is an implementation of the engine.prc.Shared service.
type SharedHandler interface {
	StreamHandler(context.Context, *connect.BidiStream[prc.SharedMessage, prc.SharedMessage]) error
}

// NewSharedHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSharedHandler(svc SharedHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sharedStreamHandlerHandler := connect.NewBidiStreamHandler(
		SharedStreamHandlerProcedure,
		svc.StreamHandler,
		connect.WithSchema(sharedStreamHandlerMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/engine.prc.Shared/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SharedStreamHandlerProcedure:
			sharedStreamHandlerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSharedHandler returns CodeUnimplemented from all methods.
type UnimplementedSharedHandler struct{}

func (UnimplementedSharedHandler) StreamHandler(context.Context, *connect.BidiStream[prc.SharedMessage, prc.SharedMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("engine.prc.Shared.StreamHandler is not implemented"))
}
