// Code generated by minotaur-config-export. DO NOT EDIT.
package configs
	 // SystemConfig 系统
type SystemConfig struct {
	Addr string // 监听地址
	Finish string // 启动完成
} 

	 // WelcomeConfig 欢迎词
type WelcomeConfig struct {
	Id int // ID
	Text string // 内容
} 

