// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.0--rc1
// source: accident_record.proto

package supervision

import (
	prc "github.com/kercylan98/minotaur/engine/prc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CrossAccidentRecord 事故记录
type CrossAccidentRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimeCulprit *prc.ProcessId       `protobuf:"bytes,1,opt,name=prime_culprit,json=primeCulprit,proto3" json:"prime_culprit,omitempty"` // 事故元凶（通常是消息发送人，可能不存在或逃逸）
	Victim       *prc.ProcessId       `protobuf:"bytes,2,opt,name=Victim,proto3" json:"Victim,omitempty"`                                 // 事故受害者
	Supervisor   *prc.ProcessId       `protobuf:"bytes,3,opt,name=Supervisor,proto3" json:"Supervisor,omitempty"`                         // 事故监管者，将由其进行决策
	Message      *prc.DeliveryMessage `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                               // 造成事故发生的消息
	Reason       string               `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                 // 事故原因
	Strategy     string               `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`                             // 监管策略名称（如果是远程监管，那么需要确保监管策略在远程方是已注册的）
	State        *CrossAccidentState  `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`                                   // 事故状态
}

func (x *CrossAccidentRecord) Reset() {
	*x = CrossAccidentRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accident_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossAccidentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossAccidentRecord) ProtoMessage() {}

func (x *CrossAccidentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_accident_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossAccidentRecord.ProtoReflect.Descriptor instead.
func (*CrossAccidentRecord) Descriptor() ([]byte, []int) {
	return file_accident_record_proto_rawDescGZIP(), []int{0}
}

func (x *CrossAccidentRecord) GetPrimeCulprit() *prc.ProcessId {
	if x != nil {
		return x.PrimeCulprit
	}
	return nil
}

func (x *CrossAccidentRecord) GetVictim() *prc.ProcessId {
	if x != nil {
		return x.Victim
	}
	return nil
}

func (x *CrossAccidentRecord) GetSupervisor() *prc.ProcessId {
	if x != nil {
		return x.Supervisor
	}
	return nil
}

func (x *CrossAccidentRecord) GetMessage() *prc.DeliveryMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CrossAccidentRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CrossAccidentRecord) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *CrossAccidentRecord) GetState() *CrossAccidentState {
	if x != nil {
		return x.State
	}
	return nil
}

type CrossAccidentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccidentTimes []*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=accident_times,json=accidentTimes,proto3" json:"accident_times,omitempty"`
}

func (x *CrossAccidentState) Reset() {
	*x = CrossAccidentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accident_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossAccidentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossAccidentState) ProtoMessage() {}

func (x *CrossAccidentState) ProtoReflect() protoreflect.Message {
	mi := &file_accident_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossAccidentState.ProtoReflect.Descriptor instead.
func (*CrossAccidentState) Descriptor() ([]byte, []int) {
	return file_accident_record_proto_rawDescGZIP(), []int{1}
}

func (x *CrossAccidentState) GetAccidentTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.AccidentTimes
	}
	return nil
}

var File_accident_record_proto protoreflect.FileDescriptor

var file_accident_record_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x02, 0x0a, 0x13, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x41,
	0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x33, 0x0a,
	0x0d, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x75, 0x6c, 0x70, 0x72, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x49, 0x64, 0x52, 0x0c, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x43, 0x75, 0x6c, 0x70, 0x72,
	0x69, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x56, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x52, 0x06, 0x56, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x12, 0x2e, 0x0a, 0x0a, 0x53, 0x75,
	0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x52, 0x0a,
	0x53, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x63, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x35,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x6f, 0x73,
	0x73, 0x41, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x57, 0x0a, 0x12, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x41, 0x63,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x61,
	0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0d, 0x61, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x42, 0x3a,
	0x5a, 0x38, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65,
	0x72, 0x63, 0x79, 0x6c, 0x61, 0x6e, 0x39, 0x38, 0x2f, 0x6d, 0x69, 0x6e, 0x6f, 0x74, 0x61, 0x75,
	0x72, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x69, 0x76, 0x69, 0x64, 0x2f, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_accident_record_proto_rawDescOnce sync.Once
	file_accident_record_proto_rawDescData = file_accident_record_proto_rawDesc
)

func file_accident_record_proto_rawDescGZIP() []byte {
	file_accident_record_proto_rawDescOnce.Do(func() {
		file_accident_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_accident_record_proto_rawDescData)
	})
	return file_accident_record_proto_rawDescData
}

var file_accident_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_accident_record_proto_goTypes = []interface{}{
	(*CrossAccidentRecord)(nil),   // 0: supervision.CrossAccidentRecord
	(*CrossAccidentState)(nil),    // 1: supervision.CrossAccidentState
	(*prc.ProcessId)(nil),         // 2: prc.ProcessId
	(*prc.DeliveryMessage)(nil),   // 3: prc.DeliveryMessage
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_accident_record_proto_depIdxs = []int32{
	2, // 0: supervision.CrossAccidentRecord.prime_culprit:type_name -> prc.ProcessId
	2, // 1: supervision.CrossAccidentRecord.Victim:type_name -> prc.ProcessId
	2, // 2: supervision.CrossAccidentRecord.Supervisor:type_name -> prc.ProcessId
	3, // 3: supervision.CrossAccidentRecord.message:type_name -> prc.DeliveryMessage
	1, // 4: supervision.CrossAccidentRecord.state:type_name -> supervision.CrossAccidentState
	4, // 5: supervision.CrossAccidentState.accident_times:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_accident_record_proto_init() }
func file_accident_record_proto_init() {
	if File_accident_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accident_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossAccidentRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accident_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossAccidentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accident_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accident_record_proto_goTypes,
		DependencyIndexes: file_accident_record_proto_depIdxs,
		MessageInfos:      file_accident_record_proto_msgTypes,
	}.Build()
	File_accident_record_proto = out.File
	file_accident_record_proto_rawDesc = nil
	file_accident_record_proto_goTypes = nil
	file_accident_record_proto_depIdxs = nil
}
