syntax = "proto3";
package engine.vivid.cluster.internal.gossip.v1;

import "engine/prc/v1/process_id.proto";

// 初始化集群，此刻节点准备尝试加入其他集群或创建集群
message GossipActorInitClusterMessage {
  int64 retry_interval_duration = 1; // 重试间隔
}

// 节点携带自身信息尝试加入集群，在收到 GossipActorTryJoinClusterAckMessage
message GossipActorTryJoinClusterMessage {
  Node node = 1; // 加入者节点信息
}

// 尝试加入集群确认消息
message GossipActorTryJoinClusterAckMessage {
  bool refuse = 1; // 拒绝
  Gossiped gossiped = 2; // 节点状态同步
  prc.v1.ProcessId handler = 3; // 处理人
}

// 创建集群消息（正常应该为本地使用）
message GossipActorCreateClusterMessage {}

// 扩散节点状态
message GossipActorSyncNodeStatusMessage {
  GossipNodeStatus status = 1; // 节点状态
  prc.v1.ProcessId node = 2; // 节点 ID
}

// 集群已收敛（正常应该为本地使用）
message GossipActorClusterConvergedMessage {}

// 节点信息
message Node {
  NodeId id = 1; // 节点 ID
  GossipNodeStatus status = 2; // 节点状态
  VectorClock vc = 3; // 矢量时钟
  int64 launch_timestamp_millis = 4; // 节点启动时间戳
  NodeState user_state = 5; // 用户状态 
}

// 节点用户状态
message NodeState {
  map<string, bool> fixed_actor_providers = 5; // 节点提供的固定 Actor Providers
  map<string, bool> only_actor_providers = 6; // 节点提供的唯一 Actor Providers
  map<string, AliveOnlyActorInfo> alive_only_actors = 7; // 节点存活的唯一 Actor 及时间戳
}

// 存活的唯一 Actor 信息
message AliveOnlyActorInfo {
  prc.v1.ProcessId ref = 1;
  int64 generate_time = 2;
}

// 节点 ID
message NodeId {
  prc.v1.ProcessId ref = 1; // 节点引用
  int64 guid = 2; // 同节点唯一标识
}

// Gossip 状态
message Gossip {
  repeated Node members = 1; // 集群成员
  repeated NodeId seen = 2; // 已seen的节点
  map<string, GossipNodeStatus> accessibility_change = 3; // 节点可达性变化
}

// Gossiped 已传播到达的状态
message Gossiped {
  Gossip gossip = 1; // gossip
  VectorClock gossiper_version = 2; // 发送者版本
}

// GossipedAckMessage 对于 Gossiped 的消息确认
message GossipedAckMessage {
  Gossiped gossiped = 1;
}

// 该消息用于表示节点需要离开集群，通常为本地发送给 GossipActor
message GossipActorLeaveClusterMessage {}

// 心跳消息
message GossipActorPingPongMessage {}

// 集群 Actor 退出中消息，该消息将会发送给其父
message GossipActorClusterExitingMessage {}

// 集群 Actor 已完成退出的通知消息，该消息将会发送给其父
message GossipActorClusterExitedMessage {}

// 节点状态
enum GossipNodeStatus {
  GOSSIP_NODE_STATUS_UNSPECIFIED = 0;
  GOSSIP_NODE_STATUS_JOINING = 1; // 加入中
  GOSSIP_NODE_STATUS_ALIVE = 2; // 活跃
  GOSSIP_NODE_STATUS_LEAVING = 3; // 正在离开
  GOSSIP_NODE_STATUS_EXITING = 4; // 退出中
  GOSSIP_NODE_STATUS_EXITED = 5; // 已退出
  GOSSIP_NODE_STATUS_REMOVED = 6; // 移除
  GOSSIP_NODE_STATUS_UNREACHABLE = 7; // 不可达
  GOSSIP_NODE_STATUS_REACHABLE = 8; // 可达（网络恢复期间缓冲）
  GOSSIP_NODE_STATUS_DOWN = 9; // 宕机
}

// 矢量时钟结构
message VectorClock {
  map<string, uint64> version = 1; // 使用 key-value 对存储每个节点的版本
}

enum VectorClockOrdering {
  VECTOR_CLOCK_ORDERING_UNSPECIFIED = 0;
  VECTOR_CLOCK_ORDERING_CONCURRENT = 1; // 并行
  VECTOR_CLOCK_ORDERING_AFTER = 2; // 之后
  VECTOR_CLOCK_ORDERING_BEFORE = 3; // 之前
  VECTOR_CLOCK_ORDERING_SAME = 4; // 相同
}