package ecs

import (
	"github.com/kercylan98/minotaur/utils/generic"
	"testing"
)

type Position struct {
	X int
	Y int
}

type Velocity struct {
	X int
	Y int
}

type Component1 struct{ X int }
type Component2 struct{ X int }
type Component3 struct{ X int }
type Component4 struct{ X int }
type Component5 struct{ X int }
type Component6 struct{ X int }
type Component7 struct{ X int }
type Component8 struct{ X int }
type Component9 struct{ X int }
type Component10 struct{ X int }
type Component11 struct{ X int }
type Component12 struct{ X int }
type Component13 struct{ X int }
type Component14 struct{ X int }
type Component15 struct{ X int }
type Component16 struct{ X int }
type Component17 struct{ X int }
type Component18 struct{ X int }
type Component19 struct{ X int }
type Component20 struct{ X int }
type Component21 struct{ X int }
type Component22 struct{ X int }
type Component23 struct{ X int }
type Component24 struct{ X int }
type Component25 struct{ X int }
type Component26 struct{ X int }
type Component27 struct{ X int }
type Component28 struct{ X int }
type Component29 struct{ X int }
type Component30 struct{ X int }
type Component31 struct{ X int }
type Component32 struct{ X int }
type Component33 struct{ X int }
type Component34 struct{ X int }
type Component35 struct{ X int }
type Component36 struct{ X int }
type Component37 struct{ X int }
type Component38 struct{ X int }
type Component39 struct{ X int }
type Component40 struct{ X int }
type Component41 struct{ X int }
type Component42 struct{ X int }
type Component43 struct{ X int }
type Component44 struct{ X int }
type Component45 struct{ X int }
type Component46 struct{ X int }
type Component47 struct{ X int }
type Component48 struct{ X int }
type Component49 struct{ X int }
type Component50 struct{ X int }
type Component51 struct{ X int }
type Component52 struct{ X int }
type Component53 struct{ X int }
type Component54 struct{ X int }
type Component55 struct{ X int }
type Component56 struct{ X int }
type Component57 struct{ X int }
type Component58 struct{ X int }
type Component59 struct{ X int }
type Component60 struct{ X int }
type Component61 struct{ X int }
type Component62 struct{ X int }
type Component63 struct{ X int }
type Component64 struct{ X int }
type Component65 struct{ X int }
type Component66 struct{ X int }
type Component67 struct{ X int }
type Component68 struct{ X int }
type Component69 struct{ X int }
type Component70 struct{ X int }
type Component71 struct{ X int }
type Component72 struct{ X int }
type Component73 struct{ X int }
type Component74 struct{ X int }
type Component75 struct{ X int }
type Component76 struct{ X int }
type Component77 struct{ X int }
type Component78 struct{ X int }
type Component79 struct{ X int }
type Component80 struct{ X int }
type Component81 struct{ X int }
type Component82 struct{ X int }
type Component83 struct{ X int }
type Component84 struct{ X int }
type Component85 struct{ X int }
type Component86 struct{ X int }
type Component87 struct{ X int }
type Component88 struct{ X int }
type Component89 struct{ X int }
type Component90 struct{ X int }
type Component91 struct{ X int }
type Component92 struct{ X int }
type Component93 struct{ X int }
type Component94 struct{ X int }
type Component95 struct{ X int }
type Component96 struct{ X int }
type Component97 struct{ X int }
type Component98 struct{ X int }
type Component99 struct{ X int }
type Component100 struct{ X int }
type Component101 struct{ X int }
type Component102 struct{ X int }
type Component103 struct{ X int }
type Component104 struct{ X int }
type Component105 struct{ X int }
type Component106 struct{ X int }
type Component107 struct{ X int }
type Component108 struct{ X int }
type Component109 struct{ X int }
type Component110 struct{ X int }
type Component111 struct{ X int }
type Component112 struct{ X int }
type Component113 struct{ X int }
type Component114 struct{ X int }
type Component115 struct{ X int }
type Component116 struct{ X int }
type Component117 struct{ X int }
type Component118 struct{ X int }
type Component119 struct{ X int }
type Component120 struct{ X int }
type Component121 struct{ X int }
type Component122 struct{ X int }
type Component123 struct{ X int }
type Component124 struct{ X int }
type Component125 struct{ X int }
type Component126 struct{ X int }
type Component127 struct{ X int }
type Component128 struct{ X int }
type Component129 struct{ X int }
type Component130 struct{ X int }
type Component131 struct{ X int }
type Component132 struct{ X int }
type Component133 struct{ X int }
type Component134 struct{ X int }
type Component135 struct{ X int }
type Component136 struct{ X int }
type Component137 struct{ X int }
type Component138 struct{ X int }
type Component139 struct{ X int }
type Component140 struct{ X int }
type Component141 struct{ X int }
type Component142 struct{ X int }
type Component143 struct{ X int }
type Component144 struct{ X int }
type Component145 struct{ X int }
type Component146 struct{ X int }
type Component147 struct{ X int }
type Component148 struct{ X int }
type Component149 struct{ X int }
type Component150 struct{ X int }
type Component151 struct{ X int }
type Component152 struct{ X int }
type Component153 struct{ X int }
type Component154 struct{ X int }
type Component155 struct{ X int }
type Component156 struct{ X int }
type Component157 struct{ X int }
type Component158 struct{ X int }
type Component159 struct{ X int }
type Component160 struct{ X int }
type Component161 struct{ X int }
type Component162 struct{ X int }
type Component163 struct{ X int }
type Component164 struct{ X int }
type Component165 struct{ X int }
type Component166 struct{ X int }
type Component167 struct{ X int }
type Component168 struct{ X int }
type Component169 struct{ X int }
type Component170 struct{ X int }
type Component171 struct{ X int }
type Component172 struct{ X int }
type Component173 struct{ X int }
type Component174 struct{ X int }
type Component175 struct{ X int }
type Component176 struct{ X int }
type Component177 struct{ X int }
type Component178 struct{ X int }
type Component179 struct{ X int }
type Component180 struct{ X int }
type Component181 struct{ X int }
type Component182 struct{ X int }
type Component183 struct{ X int }
type Component184 struct{ X int }
type Component185 struct{ X int }
type Component186 struct{ X int }
type Component187 struct{ X int }
type Component188 struct{ X int }
type Component189 struct{ X int }
type Component190 struct{ X int }
type Component191 struct{ X int }
type Component192 struct{ X int }
type Component193 struct{ X int }
type Component194 struct{ X int }
type Component195 struct{ X int }
type Component196 struct{ X int }
type Component197 struct{ X int }
type Component198 struct{ X int }
type Component199 struct{ X int }
type Component200 struct{ X int }
type Component201 struct{ X int }
type Component202 struct{ X int }
type Component203 struct{ X int }
type Component204 struct{ X int }
type Component205 struct{ X int }
type Component206 struct{ X int }
type Component207 struct{ X int }
type Component208 struct{ X int }
type Component209 struct{ X int }
type Component210 struct{ X int }
type Component211 struct{ X int }
type Component212 struct{ X int }
type Component213 struct{ X int }
type Component214 struct{ X int }
type Component215 struct{ X int }
type Component216 struct{ X int }
type Component217 struct{ X int }
type Component218 struct{ X int }
type Component219 struct{ X int }
type Component220 struct{ X int }
type Component221 struct{ X int }
type Component222 struct{ X int }
type Component223 struct{ X int }
type Component224 struct{ X int }
type Component225 struct{ X int }
type Component226 struct{ X int }
type Component227 struct{ X int }
type Component228 struct{ X int }
type Component229 struct{ X int }
type Component230 struct{ X int }
type Component231 struct{ X int }
type Component232 struct{ X int }
type Component233 struct{ X int }
type Component234 struct{ X int }
type Component235 struct{ X int }
type Component236 struct{ X int }
type Component237 struct{ X int }
type Component238 struct{ X int }
type Component239 struct{ X int }
type Component240 struct{ X int }
type Component241 struct{ X int }
type Component242 struct{ X int }
type Component243 struct{ X int }
type Component244 struct{ X int }
type Component245 struct{ X int }
type Component246 struct{ X int }
type Component247 struct{ X int }
type Component248 struct{ X int }
type Component249 struct{ X int }
type Component250 struct{ X int }
type Component251 struct{ X int }
type Component252 struct{ X int }
type Component253 struct{ X int }
type Component254 struct{ X int }
type Component255 struct{ X int }
type Component256 struct{ X int }

func ExceptNum[V generic.Number](t *testing.T, got, expect V) {
	if got != expect {
		t.Fatalf("got %v, expect %v", got, expect)
	}
}
