// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: engine/prc/shared.proto

package prc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shared_StreamHandler_FullMethodName = "/engine.prc.Shared/StreamHandler"
)

// SharedClient is the client API for Shared service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Shared 共享服务
type SharedClient interface {
	StreamHandler(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SharedMessage, SharedMessage], error)
}

type sharedClient struct {
	cc grpc.ClientConnInterface
}

func NewSharedClient(cc grpc.ClientConnInterface) SharedClient {
	return &sharedClient{cc}
}

func (c *sharedClient) StreamHandler(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SharedMessage, SharedMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Shared_ServiceDesc.Streams[0], Shared_StreamHandler_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SharedMessage, SharedMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Shared_StreamHandlerClient = grpc.BidiStreamingClient[SharedMessage, SharedMessage]

// SharedServer is the server API for Shared service.
// All implementations must embed UnimplementedSharedServer
// for forward compatibility.
//
// Shared 共享服务
type SharedServer interface {
	StreamHandler(grpc.BidiStreamingServer[SharedMessage, SharedMessage]) error
	mustEmbedUnimplementedSharedServer()
}

// UnimplementedSharedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharedServer struct{}

func (UnimplementedSharedServer) StreamHandler(grpc.BidiStreamingServer[SharedMessage, SharedMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamHandler not implemented")
}
func (UnimplementedSharedServer) mustEmbedUnimplementedSharedServer() {}
func (UnimplementedSharedServer) testEmbeddedByValue()                {}

// UnsafeSharedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharedServer will
// result in compilation errors.
type UnsafeSharedServer interface {
	mustEmbedUnimplementedSharedServer()
}

func RegisterSharedServer(s grpc.ServiceRegistrar, srv SharedServer) {
	// If the following call pancis, it indicates UnimplementedSharedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shared_ServiceDesc, srv)
}

func _Shared_StreamHandler_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SharedServer).StreamHandler(&grpc.GenericServerStream[SharedMessage, SharedMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Shared_StreamHandlerServer = grpc.BidiStreamingServer[SharedMessage, SharedMessage]

// Shared_ServiceDesc is the grpc.ServiceDesc for Shared service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shared_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.prc.Shared",
	HandlerType: (*SharedServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHandler",
			Handler:       _Shared_StreamHandler_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "engine/prc/shared.proto",
}
