// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package transport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	OnConnectionOpen(ctx context.Context, opts ...grpc.CallOption) (Service_OnConnectionOpenClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) OnConnectionOpen(ctx context.Context, opts ...grpc.CallOption) (Service_OnConnectionOpenClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/remote.Service/OnConnectionOpen", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceOnConnectionOpenClient{stream}
	return x, nil
}

type Service_OnConnectionOpenClient interface {
	Send(*DistributedMessage) error
	Recv() (*DistributedMessage, error)
	grpc.ClientStream
}

type serviceOnConnectionOpenClient struct {
	grpc.ClientStream
}

func (x *serviceOnConnectionOpenClient) Send(m *DistributedMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceOnConnectionOpenClient) Recv() (*DistributedMessage, error) {
	m := new(DistributedMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	OnConnectionOpen(Service_OnConnectionOpenServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) OnConnectionOpen(Service_OnConnectionOpenServer) error {
	return status.Errorf(codes.Unimplemented, "method OnConnectionOpen not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_OnConnectionOpen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).OnConnectionOpen(&serviceOnConnectionOpenServer{stream})
}

type Service_OnConnectionOpenServer interface {
	Send(*DistributedMessage) error
	Recv() (*DistributedMessage, error)
	grpc.ServerStream
}

type serviceOnConnectionOpenServer struct {
	grpc.ServerStream
}

func (x *serviceOnConnectionOpenServer) Send(m *DistributedMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceOnConnectionOpenServer) Recv() (*DistributedMessage, error) {
	m := new(DistributedMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnConnectionOpen",
			Handler:       _Service_OnConnectionOpen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "network.proto",
}
