syntax = "proto3";
package engine.datasheet.v1;

// 生成数据表请求
message GenerateDataSheetRequest {
  Pos data_sheet_name_pos = 1; // 数据表名称位置
  FieldScannerConfig field_scanner_config = 2; // 字段扫描配置
  DataSheetRaw data_sheet_raw = 100; // 数据表源数据
}

// 生成数据表响应
message GenerateDataSheetResponse {
  DataSheet data_sheet = 1;
}

// 数据表
message DataSheet {
  string name = 1; // 数据表名称
  string description = 2; // 数据表描述
  repeated DataSheetField fields = 3; // 数据表字段
  string error = 4; // 错误信息
}

// 数据表字段信息
message DataSheetField {
  string name = 1; // 名称
  string description = 2; // 描述
  repeated string groups = 3; // 所属分组
  DataSheetStruct struct_info = 4; // 结构信息
}

// 数据表结构信息
message DataSheetStruct {
  DataSheetStructType type = 1; // 字段类型
  string name = 2; // 结构名称
  string description = 3; // 描述
  bool is_optional = 4; // 是否可选
  string field_name = 5; // 作为字段的名称
  oneof type_info_oneof {
    DataSheetStructInfo struct_info = 1000;
    DataSheetArrayInfo array_info = 1001;
    DataSheetSliceInfo slice_info = 1002;
    DataSheetMapInfo map_info = 1003;
  }
}

message DataSheetStructInfo {
  repeated DataSheetStruct fields = 5; // 结构字段
}

message DataSheetArrayInfo {
  int32 length = 1; // 长度
  DataSheetStruct struct_info = 2; 
}

message DataSheetSliceInfo {
  DataSheetStruct struct_info = 1;
}

message DataSheetMapInfo {
  DataSheetStruct key_struct_info = 1;
  DataSheetStruct value_struct_info = 2;
}

// 结构类型
enum DataSheetStructType {
  DATA_SHEET_FIELD_TYPE_UNSPECIFIED = 0; 
  DATA_SHEET_FIELD_TYPE_BOOLEAN = 1;
  DATA_SHEET_FIELD_TYPE_INT = 2;
  DATA_SHEET_FIELD_TYPE_INT8 = 3;
  DATA_SHEET_FIELD_TYPE_INT16 = 4;
  DATA_SHEET_FIELD_TYPE_INT32 = 5;
  DATA_SHEET_FIELD_TYPE_INT64 = 6;
  DATA_SHEET_FIELD_TYPE_UINT = 7;
  DATA_SHEET_FIELD_TYPE_UINT8 = 8;
  DATA_SHEET_FIELD_TYPE_UINT16 = 9;
  DATA_SHEET_FIELD_TYPE_UINT32 = 10;
  DATA_SHEET_FIELD_TYPE_UINT64 = 11;
  DATA_SHEET_FIELD_TYPE_FLOAT = 12;
  DATA_SHEET_FIELD_TYPE_DOUBLE = 13;
  DATA_SHEET_FIELD_TYPE_STRING = 14;
  DATA_SHEET_FIELD_TYPE_Byte = 15; 
  DATA_SHEET_FIELD_TYPE_TIME = 16;
  DATA_SHEET_FIELD_TYPE_FLOAT32 = 17;
  DATA_SHEET_FIELD_TYPE_FLOAT64 = 18;
  DATA_SHEET_FIELD_TYPE_SHORT = 19;
  DATA_SHEET_FIELD_TYPE_LONG = 20;
  DATA_SHEET_FIELD_TYPE_STRUCT = 21;
  DATA_SHEET_FIELD_TYPE_ARRAY = 22;
  DATA_SHEET_FIELD_TYPE_SLICE = 23;
  DATA_SHEET_FIELD_TYPE_MAP = 24;
  DATA_SHEET_FIELD_TYPE_LIST = 25;
  DATA_SHEET_FIELD_TYPE_BOOL = 26;
  DATA_SHEET_FIELD_TYPE_BIGINT = 27;
  DATA_SHEET_FIELD_TYPE_BIGFLOAT = 28;
}

// 加载数据表请求
message LoadDataSheetFileRequest {
  bytes binary_data = 1; // 二进制数据
}

// 加载数据表响应
message LoadDataSheetFileResponse {
  repeated LoadDataSheetFailedInfo load_data_sheet_failed_infos = 1; // 加载失败的数据表
  repeated DataSheetRaw data_sheet_raws = 2; // 数据表原始数据
}

// 加载失败的数据表
message LoadDataSheetFailedInfo {
  string name = 1; // 数据表可读名称
  string err = 2; // 错误信息
}

// 数据表源数据
message DataSheetRaw {
  int32 index = 1;// 数据表索引
  string name = 2; // 数据表可读名称（Sheet 名）
  repeated DataSheetRawRow rows = 3; // 行
}

// 行
message DataSheetRawRow {
  repeated DataSheetRawCell cells = 1; // 列
}

// 列
message DataSheetRawCell {
  string value = 1; // 值
}

// 定位
message Pos {
  int32 row = 1; // 从 0 开始
  int32 cell = 2; // 从 0 开始
}

message FieldScannerConfig {
  Pos name_start_pos = 1; // 字段名称开始位置
  Pos name_next_delta_pos = 2; // 字段名称下一个位置的偏移量
  Pos type_start_pos = 3; // 字段类型开始位置
  Pos type_next_delta_pos = 4; // 字段类型下一个位置的偏移量
  Pos groups_start_pos = 5; // 字段分组开始位置
  Pos groups_next_delta_pos = 6; // 字段分组下一个位置的偏移量
  Pos description_start_pos = 7; // 字段描述开始位置
  Pos description_next_delta_pos = 8; // 字段描述下一个位置的偏移量
}