// Code generated by minotaur-config-export. DO NOT EDIT.
package example
	 // XXConfig 有索引
type XXConfig struct {
	Id int // 任务ID
	Count string // 次数
	Info *XXConfigInfo // 信息
	Other map[int]*XXConfigOther // 信息2
} 

type XXConfigInfo struct {
	Id int
	Name string
	Info *XXConfigInfoInfo
} 

type XXConfigInfoInfo struct {
	Lv int
	Exp *XXConfigInfoInfoExp
} 

type XXConfigInfoInfoExp struct {
	Mux int
	Count int
} 

type XXConfigOther struct {
	Id int
	Name string
} 

	 // UNConfig 无索引
type UNConfig struct {
	Id int // 任务ID
	Count string // 次数
	Info *UNConfigInfo // 信息
	Other map[int]*UNConfigOther // 信息2
} 

type UNConfigInfo struct {
	Id int
	Name string
	Info *UNConfigInfoInfo
} 

type UNConfigInfoInfo struct {
	Lv int
	Exp *UNConfigInfoInfoExp
} 

type UNConfigInfoInfoExp struct {
	Mux int
	Count int
} 

type UNConfigOther struct {
	Id int
	Name string
} 

