// Code generated by minotaur-config-export. DO NOT EDIT.
package example
	 // IndexConfig 有索引
type IndexConfig struct {
	Id int // 任务ID
	Count string // 次数
	Info *IndexConfigInfo // 信息
	Other map[int]*IndexConfigOther // 信息2
} 

type IndexConfigInfo struct {
	Id int
	Name string
	Info *IndexConfigInfoInfo
} 

type IndexConfigInfoInfo struct {
	Lv int
	Exp *IndexConfigInfoInfoExp
} 

type IndexConfigInfoInfoExp struct {
	Mux int
	Count int
} 

type IndexConfigOther struct {
	Id int
	Name string
} 

	 // EasyConfig 无索引
type EasyConfig struct {
	Id int // 任务ID
	Count string // 次数
	Info *EasyConfigInfo // 信息
	Other map[int]*EasyConfigOther // 信息2
} 

type EasyConfigInfo struct {
	Id int
	Name string
	Info *EasyConfigInfoInfo
} 

type EasyConfigInfoInfo struct {
	Lv int
	Exp *EasyConfigInfoInfoExp
} 

type EasyConfigInfoInfoExp struct {
	Mux int
	Count int
} 

type EasyConfigOther struct {
	Id int
	Name string
} 

